config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  
  get 'home/homepage'

  get 'home/about'

  get 'home/contact'
  
  get 'home/links'
  
  get 'home/article_template'
  
  get 'pages/gdansk'

  get 'pages/gdansk_bary'

  get 'pages/gdansk_kawiarnie'

  get 'pages/gdansk_restauracje'

  get 'pages/sopot'

  get 'pages/sopot_bary'

  get 'pages/sopot_kawiarnie'

  get 'pages/sopot_restauracje'

  get 'pages/gdynia'

  get 'pages/gdynia_bary'

  get 'pages/gdynia_kawiarnie'

  get 'pages/gdynia_restauracje'

 
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def gdansk
  end

  def gdansk_bary
  end

  def gdansk_kawiarnie
  end

  def gdansk_restauracje
  end

  def sopot
  end

  def sopot_bary
  end

  def sopot_kawiarnie
  end

  def sopot_restauracje
  end

  def gdynia
  end

  def gdynia_bary
  end

  def gdynia_kawiarnie
  end

  def gdynia_restauracje
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/home/_header.html.erb
<div class = "containerHeader">
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
      </button>
      <center><a class="navbar-brand">3CityTastes</a></center>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Gdynia', pages_gdynia_path %></li>
        <li><%= link_to 'Gdańsk', pages_gdansk_path %></li>
        <li><%= link_to 'Sopot', pages_sopot_path %></li>
        
      </ul>
      <!--<a class="brand" style="margin: 0; float: none;" href="#">
                <img url="logo.jpg" />
                </a>-->
                
      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Strona główna', home_homepage_path %></li>
            <li><%= link_to 'O nas', home_about_path %></li>
             <li><%= link_to 'Kontakt', home_contact_path %></li>
        <li><%= link_to 'Linki', home_links_path %></li>
      
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</div>

app/views/home/about.html.erb
<div class = "infocontainer">
    <div class = "annbox">
        <div class = "abphoto"> </div>
        <div class = "abinfo"> <p id="pfirst"><strong>Ania Bach</strong></p><br>
        <p>
            Studentka chemii na Politechnice Gdańskiej.
W pełni zainteresowana światem chemii, dietetyki, fitness, tańca.
Kocha chodzić do łóżka z książkami.
Amatorka gotowania i fotografii. Kinomanka.
Z charakteru mała, wredna istotka, lubiąca robić na przekór, pokazując że się da.
Potrafi wysłuchać, umie doradzić.
Jej hobby to jedzenie. Ziemniaczane, makaronowe, warzywne, mięsne, czekoladowe…
Uwielbia odkrywać smaki różnych knajp.
Utożsamia się z twierdzeniem: Jeśli nie lubisz słodyczy, jesteś złym człowiekiem.
</p> </div>
    </div>
    

    <div class = "maksbox">
        <div class = "mzphoto"></div>
        <div class = "mzinfo" id="mzimg"> <p><strong>Maksym Zielński</strong><br><br>
Dla przyjaciół Linux, dla bratniej duszy Maksio.<br>
Student Gdańskiej Politechniki, na kierunku Informatyka Stosowana.
Z zamiłowania programista, majster od sprzętu, gracz komputerowy.<br>
Z charakteru bywa szczery do bólu, ale w środku  wrażliwy i nader cierpliwy, pomocy nigdy nie odmówi. Kocha muzykę wszelkiego rodzaju, jest ciekawy świata, przejmuje się polityką naszego kraju, jednak jeśli chodzi o historię, to zna lepiej Chiny.
Uwielbia jedzenie, od słodkiego, do ostrego. Najbardziej lubi mięso i ser pleśniowy.<br> Nie przepada za słodyczami (czekolada, lody i ciasta to nie słodycze).
Utożsamia się z twierdzeniem: Jedzenie to najważniejszy posiłek dnia.</p></div>
    </div>
    
    
</div>

app/views/home/article_template.html.erb
<div class="container">

        <div class="row">

            <!-- Blog Post Content Column -->
            <div class="postarea">

                <!-- Blog Post -->

                <!-- Title -->
                <h1 class = "reviewheader"><center>TITLE</center></h1>

                <!-- Author -->
                <p class="lead">
                  od  <a href="#">AUTOR</a>
                </p>

                <hr class = "posthr">

                <!-- Date/Time -->
                <p><span class="glyphicon glyphicon-time"></span> Posted on DATE </p>

                <hr class = "posthr">


                <!-- Preview Image -->
                
                <center><%= image_tag("", :alt => "rss feed") %></center> <!--IMAGE IN "" -->
				        


                <hr class = "posthr">


                <!-- Post Content -->
                <div class='reviewspace'><p>
                Text here
                <!-- Side Widget Well -->
            </div>
        </div>

app/views/home/contact.html.erb
<h1>Home#contact</h1>
<p>Find me in app/views/home/contact.html.erb</p>

app/views/home/homepage.html.erb
<div class = "homepagecontainer">
    <div class = "mainframephotos">
        
        <a href="/pages/gdynia"><div class = "gdyniaphoto" id="gdyp"> </div></a>
        <a href="/pages/gdansk"><div class = "gdanskphoto" id="gdap"></div></a>
        <a href="/pages/sopot"><div class = "sopotphoto" id="sopp"></div></a>
        
    </div>
</div>


<div class = "lastarticlesone">
        
</div>


<div class = "lastarticlestwo">
    
</div>    


<script src = "/assets/imageswapgdy.js"></script>

app/views/home/index.html.erb
<div class="WelcomePage">
    <div class = "btn-welcome-background">
<center><p><a class="btn-welcome" href="/home/homepage" role="button"></a></p></center>
  </div>
</div>

app/views/home/links.html.erb
nothing yet

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
<title>3CT</title>
</style>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>

</head>
<body>
  <div id="wrapper">
		<div id="header">
		</div>
		<div id="content">
		  <%=render 'home/header'%>
		  <%= yield %>
		</div>
		
		
  <div class="myfooter">
   
        
          <center>
            <span><a id="fblink"><img src="https://threecitytastes-joogway.c9users.io/assets/fb-icon.png" id="fbicon"></img></a><a><img src="https://threecitytastes-joogway.c9users.io/assets/insta-icon.png" id="instaicon"></img></a></span>
            Copyright &copy; 3CityTastes 2016</center>
     
  </div>

	</div>
  <script></script>
	


</html><!DOCTYPE html>

app/views/pages/gdansk.html.erb
<h1>Pages#gdansk</h1>
<p>Find me in app/views/pages/gdansk.html.erb</p>

app/views/pages/gdansk_bary.html.erb
<h1>Pages#gdansk_bary</h1>
<p>Find me in app/views/pages/gdansk_bary.html.erb</p>

app/views/pages/gdansk_kawiarnie.html.erb
<h1>Pages#gdansk_kawiarnie</h1>
<p>Find me in app/views/pages/gdansk_kawiarnie.html.erb</p>

app/views/pages/gdansk_restauracje.html.erb
<h1>Pages#gdansk_restauracje</h1>
<p>Find me in app/views/pages/gdansk_restauracje.html.erb</p>

app/views/pages/gdynia.html.erb
<h1>Pages#gdynia</h1>
<p>Find me in app/views/pages/gdynia.html.erb</p>

app/views/pages/gdynia_bary.html.erb
<h1>Pages#gdynia_bary</h1>
<p>Find me in app/views/pages/gdynia_bary.html.erb</p>

app/views/pages/gdynia_kawiarnie.html.erb
<h1>Pages#gdynia_kawiarnie</h1>
<p>Find me in app/views/pages/gdynia_kawiarnie.html.erb</p>

app/views/pages/gdynia_restauracje.html.erb
<h1>Pages#gdynia_restauracje</h1>
<p>Find me in app/views/pages/gdynia_restauracje.html.erb</p>

app/views/pages/sopot.html.erb
<h1>Pages#sopot</h1>
<p>Find me in app/views/pages/sopot.html.erb</p>

app/views/pages/sopot_bary.html.erb
<h1>Pages#sopot_bary</h1>
<p>Find me in app/views/pages/sopot_bary.html.erb</p>

app/views/pages/sopot_kawiarnie.html.erb
<h1>Pages#sopot_kawiarnie</h1>
<p>Find me in app/views/pages/sopot_kawiarnie.html.erb</p>

app/views/pages/sopot_restauracje.html.erb
<h1>Pages#sopot_restauracje</h1>
<p>Find me in app/views/pages/sopot_restauracje.html.erb</p>